#!/usr/bin/env python3
"""
Pack every app icon into one sprite sheet.

40 separate <img> tags meant 40 requests that couldn't even start until the JS
had parsed and built the grid. One sprite is one request, and it can be
preloaded from the HTML head so it downloads alongside the code.

Run from the project root:  python3 tools/build-sprite.py
"""
import json
import pathlib
import subprocess
import sys
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = ROOT / "assets" / "icons"
COLS = 8
TILE = 120


def main():
    files = sorted(ICONS.glob("*.png"))
    if not files:
        sys.exit("no icons found in assets/icons")

    rows = -(-len(files) // COLS)          # ceiling division
    sheet = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
    index = {}

    for n, path in enumerate(files):
        icon = Image.open(path).convert("RGBA")
        if icon.size != (TILE, TILE):
            icon = icon.resize((TILE, TILE), Image.LANCZOS)
        col, row = n % COLS, n // COLS
        sheet.paste(icon, (col * TILE, row * TILE))
        index[path.stem] = n

    png = ROOT / "assets" / "sprite.png"
    webp = ROOT / "assets" / "sprite.webp"
    sheet.save(png)

    # cwebp beats Pillow's encoder noticeably on flat icon art
    subprocess.run(["cwebp", "-q", "88", "-quiet", str(png), "-o", str(webp)], check=True)
    png.unlink()

    (ROOT / "js" / "sprite.js").write_text(
        "// GENERATED by tools/build-sprite.py — do not edit by hand.\n"
        "// Where each icon sits in assets/sprite.webp.\n"
        f"export const COLS = {COLS};\n"
        f"export const ROWS = {rows};\n"
        f"export const INDEX = {json.dumps(index, indent=2, sort_keys=True)};\n"
    )

    kb = webp.stat().st_size / 1024
    print(f"{len(files)} icons -> {COLS}x{rows} sheet, {kb:.0f} KB webp")


if __name__ == "__main__":
    main()
